lib/components/ModalPortal.js
For some reason componentWillReceiveProps is being called with identical props. We need to compare previous props with new props to make sure state is changing from closed to open before calling this.open(). Otherwise we're calling this.open() even when state isn't changing. Same with this.close().
=> [fixed] ModalPortal's componentWillReceiveProps

lib/components/ModalPortal.js, specs/Modal.spec.js
This makes it so you can pass a style prop to the ReactModal component
which will be added to the contents of the modal.  This is really
nice for instances where adding a className isn't appropriate such
as when position needs to be set dynamically.
=> [added] Ability to specify style for the modal contents

lib/components/ModalPortal.js, package.json
classSet / cx will be removed in a future version of React. 
This also removes the following warning when running the test suite:
WARN: 'Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset'
See also:
https://github.com/facebook/react/commit/b6980ab9809fc3ddc68c20129618f0414d49b2a4
https://www.npmjs.com/package/classnames
=> Use classnames instead of react/lib/cx

lib/helpers/focusManager.js
A race condition happens if you open a new window before closing the modal, as opening a new window has the side effect of blurring the current window.
=> Check if modalElement exists in handleFocus.

lib/helpers/injectCSS.js
Got `unknown runtime error` when `innerHTML` run on IE8, so I added conditional statement to set style by `cssText` when running on IE8 .
=> [fixed] 'unknow runtime error' in IE8

package.json
This makes it a bit more compatible with the way peerDependencies will work in `npm@3` later down the line.
It also makes it so that consumers of the lib can have another version of classnames at the app level while
not requiring this particular lib to require a version bump.  Plus, this lib sorta depends on it and should
it need to be locked down to a particular version, this lib should manage that rather than expect it to
happen at the app level.
=> Moves classnames to dependencies

lib/components/ModalPortal.js
If you try to close a modal, then unmount it from the render tree before it's done with its close animation, the `closeWithoutTimeout` call still fires, which causes a harmless JS error about settings state on an unmounted component.  Canceling the `closeWithoutTimeout` call avoids this error.
=> [fixed] Clear the closeWithTimeout timer before unmounting

lib/helpers/ariaAppHider.js
I just added check if the component is running in browser or node.
Before when rendering on server there was an error 
```
/Users/dino/Documents/dino/react-modal/lib/helpers/ariaAppHider.js:4
if (document) {
^
ReferenceError: document is not defined
```
=> added suport for isomorphic rendering

lib/components/Modal.js
In 0.14, this is required so that the modal children of access to the context.
=> Use renderSubtreeIntoContainer to keep context.

package.json
Ignore ReactDOM in browserify-shim config, so it not gets included in final build.
=> Fix build for 0.6

lib/components/ModalPortal.js, specs/Modal.spec.js
This makes it so if you provide a custom className it will override
all the default styling, relying solely on the style props you pass
in and the className itself.
Prior to this commit, providing a className or overlayClassName
doesn't really have any effect because the style attribute has higher
precedent when applying styles.
=> [fixed] Custom classnames override default styles

lib/components/ModalPortal.js
Following problem is happened in my app.
- Close modal with ESC key
- HttpRequest which runs after closing modal is canceled
- Because of ESC key
=> [Fixed] Prevent default behavior of ESC key

lib/helpers/scopeTab.js, specs/Modal.spec.js
Fixes https://github.com/rackt/react-modal/issues/44
=> [fixed] Handle case when no tabbable element exists

package.json
Without `webpack` dependency the `dev-examples` script doesn't work (unless you have `webpack` installed globally) and the example files aren't built.
=> add missing webpack devDependency

README.md, lib/components/Modal.js, lib/components/ModalPortal.js, package.json, specs/Modal.spec.js, specs/helper.js
This is an important ability since in some cases we don't want the modal to be closed when users are clicking outside.
=> [added] The ability to decide whether the modal should be closed when clicking the overlay area

lib/helpers/scopeTab.js, specs/Modal.spec.js
A follow up to https://github.com/reactjs/react-modal/pull/120.
This is a better way to handle the case when no tabbable elements are found within the modal's content.
The focus should be kept inside the modal the same way it's kept when there are some elements.
=> Fix no tabbable focus

lib/components/Modal.js, lib/helpers/ariaAppHider.js, specs/Modal.spec.js
Maybe I have misunderstood, but this commit will anchor the modal to the specified appElement, as I had expected it to from the README. It fixes https://github.com/rackt/react-modal/issues/107.
=> [fixed] Restore Modal.setAppElement() functionality

lib/components/Modal.js, specs/Modal.spec.js
This fixes a bug where if a modal was unmounted without closing first, the `ReactModal__Body--open` stays on the `body` element.
This causes issues when, for example, you have a react-router link in a modal that takes you directly to another route handler component. The expected behavior for this is the modal closes and all page state related to the modal having been open is reset.
=> [fixed] Remove ReactModal__Body--open class when unmounting Modal

package.json
Just some `package.json` changes to add support for React 15. Fixes issue #151 
Testing done:
- `npm run start` example works without any errors or warnings in Chrome 49 on Windows and Firefox 44 on Windows
- `npm run test` reports no errors
From what I see, it's safe to merge.
=> [changed] Fixes #151 adds support for React 15

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This commit adds templates for pull requests and issues.
The goal is to help those contributing to the project to
get their issues handled quicker and their pull requests
reviewed and merged quicker and more efficiently.
Please review these changes and let me know if this is something that the community here
would be willing to do.
=> Add extra information for contributors

README.md
As this has been a source of confusion not only within the issues section of this repo, but also within my software consultancy, I am proposing the addition of the included 'testing gotchas' section to the readme.
=> Update README.md to include testing gotchas

README.md, examples/basic/app.js, lib/components/Modal.js, lib/components/ModalPortal.js, specs/Modal.spec.js
Hi,
This patch would help to sync the refs to be accessed from the Component  (so, no need for a `setTimeout`). I've used the suggested name for the callback in #50 `onAfterOpen`.
This would help with #50 and #51.
Hope I followed the contribute guide.
=> [added] trigger onAfterOpen callback when available.

.babelrc, package.json, scripts/build, webpack.config.js, webpack.dist.config.js
This allows us to remove the dependency on browserify
completely.
The problem is that the size of the compiled library is 719 kB unminified and 190 kB minified.  The current implementation via browserify produces 49 kB unminified and 21 kB minified.  That's quite the difference.
Any ideas on how to get that down?
=> Move to using webpack for building the library

lib/components/Modal.js
Fixes #160.
`
Error:
Uncaught TypeError: Cannot delete property 'ref' of #<Object>.
`
=> [fixed] moved sanitizeProps() out of the renderPortal call.

scripts/build
Fixes #163 .
-  Adds back a non-minified build
This commit removes the `-p` flag from the call to webpack
so that the webpack config works as intended, creating two
files in the dist directory, one minified and one unminified.
After 3f323381b1e8c43fdbf172813b9e8a4ace9abe79 was merged the
build ended up only producing the production minified versions
for both files.  This commit restores the initial behavior
of a non-minified and a minified file.
=> [fixed] Make the non-minified dist build present again

lib/components/Modal.js, specs/Modal.spec.js
In c13fed9f3a1270a4ecfb6faf24355f2791948c00 behavior was changed
so that the modal portal ended up rendering into the app element.
In the default case where the appElement receives aria-hidden
when the modal is open, this meant that the modal itself was
also contained inside the aria-hidden element.  This limits the
ability for screenreaders to read the modal contents.
Server-side rendering should not be affected by this change
because componentDidMount is only fired on the client-side thus
having a reference to document.body there should be acceptable.
- Make the portal append to body rather than the app element
- Make sure that you are setting an app element (rather than using the default document.body) so that modal contents …
=> [fixed] Make the modal portal render into body again

lib/components/ModalPortal.js, specs/Modal.spec.js
Continuation of the fix #134. Look at this PR (#134) for more information.
- added spec to validate the fix.
- commits were not squashed to preserve the commit made by @CompuIves.
Thanks, @CompuIves.
=> [fixed] clear the delayed close timer when modal opens again.

README.md
- Makes the primary Usage example more idiomatic and consistent with the example in https://github.com/reactjs/react-modal#testing.
N/A
=> [doc] fix onRequestClose callback in Usage

webpack.dist.config.js
Fixes #209.
- Change the externals prop in the webpack dist config to an object with the correct React and ReactDOM names on the root object.
Currently, if not using any kind of module loader, webpack falls back to looking for dependencies on the root (e.g. `window` in the browser). React and ReactDOM both have different names when looking up on the root, and these different names can be specified by making the `externals` prop an object where the values represent an object of loader type => name.
See [react-redux's webpack config](https://github.com/reactjs/react-redux/blob/master/webpack.config.js) for an example.
=> [fixed] Corrects webpack distribution config externals. (#209)

README.md, lib/components/Modal.js, specs/Modal.spec.js
- new `portalClassName` prop to change the *ReactModalPortal* class.
~~Upgrade Path (for changed or removed APIs):~~
_____________
Thanks for this project! 
What do you think about adding this?
I think this is useful because:
- code can be cleaner when also using custom content and overlay classnames. If using *BEM* classes, it makes more sense to have a DOM like `.CustomModal > (.CustomModal-content + .CustomModal-overlay)` and not like `.ReactModalPortal > (.CustomModal-content + .CustomModal-overlay)`.
- my current use case is opening a modal from a content-script in an browser extension. I want to be able to target the portal DOM element precisely in order to prevent conflicts with the page css.
Few questions on my side:
- I went with …
=> [added] ability to change default 'ReactModalPortal' class

lib/components/ModalPortal.js, specs/Modal.spec.js
- If the user perform a mouse down and up only on the overlay: close the modal
- If the user perform a mouse down on the overlay, then a mouse up on the content: do nothing
- If the user perform a mouse down on the content, then a mouse up on the overlay: do nothing
Moreover, I tried to avoid the use of stopPropagation.
And it should also fix the [issue#131](https://github.com/reactjs/react-modal/issues/131) resolved by @abhijitkane in his [pull request](https://github.com/reactjs/react-modal/pull/197) by handling this problem with mouse down events only and stopPropagation.
finally, I'm not really sure if it's a bug fix or not... :)
=> Close modal when mouseDown and MouseUp happen only on the overlay

lib/components/ModalPortal.js, specs/Modal.spec.js
Fixes #220.
- Before focusing on the content div, check to see that the currently focused element isn't a descendent of the content div, to respect any focusing the application may have already done.
=> [fixed] Don't steal focus from a descendent when rendering

README.md, lib/components/Modal.js, lib/components/ModalPortal.js, specs/Modal.spec.js
Fixes #236.
- Add a aria-label to the modal content
- Existing modals should add a `contentLabel` prop describing the modal content
=> [added] Add contentLabel prop to put aria-label on modal content

README.md
- document the `ReactModal__Body--open` so people dare to use it (with a body scroll example)
=> Document ReactModal__Body--open so people dare to use it

lib/components/Modal.js, specs/Modal.spec.js
- Reset `aria-hidden` on appElement when modal is unmounted without closing
=> Ensure aria-hidden on appElement is reset on unmount

README.md
To accommodate the change in `v1.6.0`, I'd recommend to add required props info to README so that people will have it adapted beforehand.
=> added required props info to README

package.json
This should work to handle the cases mentioned in #238 as well as the discussion surrounding #245 .
We could also at some point in the future look at using [babel-plugin-transform-object-assign](https://www.npmjs.com/package/babel-plugin-transform-object-assign)
=> Bumps lodash.assign to 4.2.0

lib/components/ModalPortal.js
**Fixes #93** 
**Changes proposed:**
I have no idea why we have to use closeTimeoutMS together with onRequestClose.
**Acceptance Checklist:**
=> [fixed] closeTimeoutMS doesn't work without onRequestClose

package.json
Though this is not react-modal library's problem, here is a tweak fix necessary for TypeScript project.
Please see below post for more details:
http://stackoverflow.com/questions/41077055/typescript-2-1-feature-of-implicit-import-not-working
FYI
"Untyped imports" Section:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html
```ts
// Succeeds if `node_modules/asdf/index.js` exists
import { x } from "asdf";
```
=> [fixed] Add file extention to entry point for TypeScript importing

examples/basic/app.js, lib/components/ModalPortal.js
- Make use of es6 modules
https://github.com/reactjs/react-modal/pull/296/commits/959ec21d0ff0dcabaa712702bebe479e8cb932ee
We change to use es6 modules or rewrite it to `require('../../lib/index').defalut`.
I think it would be better to use es6 modules.
- Fix `this` scope
https://github.com/reactjs/react-modal/pull/296/commits/262e40d8b1c819d7833b95cd1b212091bce16838
=> Fix an example

lib/components/Modal.js, lib/helpers/ariaAppHider.js, lib/index.js, specs/Modal.spec.js
=> Get rid of CommonJS module

README.md
We use `const` in README.md's sample.
=> Modify the sample code to es2015 syntax in README.md

lib/components/ModalPortal.js, specs/Modal.spec.js
Fixes #304.
- [✔️] All commits have been squashed to one.
- [✔️] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [✔️] Documentation (README.md) and examples have been updated as needed.
- [✔️] If this is a code change, a spec testing the functionality has been added.
- [✔️] If the commit message has [changed] or [removed], there is an upgrade path above.
=> [fixed] Enable click to close in iOS (#301) (#304)

lib/components/Modal.js, lib/components/ModalPortal.js, specs/Modal.spec.js
Fixes #17.
- wait before unmounting the portal if `closeTimeoutMS` is set
- full details in commit message
- The upgrade path is to undo any workarounds or hacks (e.g. manually triggering the close animation before unmounting the `Modal`), though due to the lack of activity on the referenced issue, I'm guessing most users won't be affected?
=> [fixed] respect closeTimeoutMS during unmount

specs/Modal.spec.js, specs/helper.js
=> [chore] use afterEach to cleanup modals automatically.

lib/components/Modal.js, lib/components/ModalPortal.js
fixes #336 
rewrite removePortal as es5 function
Uglifyjs doesn't know anything about es6, so 1.7.0 breaks my build script with error
```
ERROR in index_586f597d6f9d7177eb8b.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/react-modal/lib/components/Modal.js:103,0]
```
=> [fixed] remove es6 style functions.

lib/components/Modal.js
This fixes this warning from react in the console without breaking functionality:
```
Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See Modal
```
Fixes #344.
This doesn't fix a bug or change the API, it should be basically a "silent" change.
=> Remove .bind(this) from removePortal call

README.md
https://github.com/reactjs/react-modal/issues/351
=> Update README for issue close modal when user click on overlay

lib/components/Modal.js
Fixes #344, fixes #348.
- Fixes the binding of the `removePortal` call in the `setTimeout` callback
by capturing a this reference in a variable in the closure scope.
Doesn't use `bind` which apparently causes warnings.
n/a
=> [fixed] remove portal context in timeout

specs/Modal.spec.js, src/components/Modal.js, src/helpers/ariaAppHider.js
This makes getAppElement a required prop as well as makes
it a function that will be called expecting a DOMElement.
closes #287
This also takes some inspiration from #359 for handling arrays
of objects.
- Remove appElement in all it's forms
- Add getAppElement as a function prop
- If you had specified an appElement via `Modal.setAppElement`,
then you need to convert that to a getAppElement prop on the
modal, this should be a function that returns either a single
element or an array of elements.
- If you had nothing specified you will need to add the getAppElement
element to prevent breakages.
=> [changed] Replace appElement with getAppElement

lib/components/Modal.js, lib/helpers/refCount.js, specs/Modal.spec.js
Keep a reference of all modals in order to manage
when to add/remove classes and aria from elements
correctly.
This solution is based on @MarkMurphy's idea #308, but it uses a simple list
to work on IE (don't really support Set).
Fixes #218 #231 #308.
=> [fix] keep references of modals.

lib/components/Modal.js, package.json, yarn.lock
Fixes #366. Also supersedes #368, #372 and #373.
- Add `prop-types` as a dependency (npm & yarn)
- Replace `React.PropTypes` with `PropTypes`
=> Use prop-types

README.md
Use callback style ref in the example of README since string refs are considered legacy and may be removed in the future.
N/A
=> Use callback style ref in readme

docs/README.md, docs/styles/classes.md, lib/components/Modal.js, specs/Modal.spec.js
This is a backport of @cassln's feature to version 1.8.x.
Original PR is #330.
Fixes #388.
- Allow to define a custom class to append on document.body.
- None ('ReactModal__Body--open' is still the default class).
=> [change] allow to customize the react-modal document.body open class.

lib/components/Modal.js
Related to #366.
- Rename the missing PropType, to stop this warning :
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`
=> fix react proptypes warning

Makefile, scripts/repo_status
If the working tree is not clean, ask if it's ok to proceed.
=> [chore] ask before publishing, in case working tree is not clean.

.gitignore, CHANGELOG.md, Makefile, scripts/changelog.py
- it's a temporary solution for update the `CHANGELOG.md`.
- added to the pipeline for releasing a new version.
- the changelog script can be ported to javascript, but python also does a great job.
=> [chore] added script to regenerate all the CHANGELOG.md.

package.json, specs/Modal.events.spec.js, specs/Modal.spec.js, specs/Modal.style.spec.js, specs/helper.js
- Upgrade React to the latest version
- Remove the deprecated `react-addons-test-utils` in favor of accessing from `react-dom/test-utils`
-
=> [chore] upgrade React devDeps to 15.6

src/components/Modal.js
- Early return if the modal is closed and will remain closed. This prevents us from doing additional DOM check and running `renderPortal` again unnecessarily. This was my original intention with https://github.com/reactjs/react-modal/pull/328, but is greatly simplified with v2 code.
I wasn't exactly sure if we wanted another test as all current tests are passing and this one (https://github.com/reactjs/react-modal/blob/master/specs/Modal.spec.js#L233) covers the scenario of multiple modals rendering. 
=> [fixed] Eliminate unnecessary renders when modal is closed

src/components/ModalPortal.js
Maybe fixes #315.
Issue #315 seems to be a problem with inconsistent state when using react-modal with `redux` [1] (all errors seems to be reported by developer using redux).
It's not a proper fix since this behaviour was not reproduced, but it should be safe.
[1] - maybe a redux and/or component state async update. (?)
- don't try to focus if `this.content` is not available.
- Uses bound ref functions instead of arrow functions, as suggested by https://facebook.github.io/react/docs/refs-and-the-dom.html#caveats
=> [fixed] incorrect focusAfterRender on componentDidUpdate.

docs/README.md
=> [chore] update installation documentation.

.eslintrc, README.md, docs/README.md, examples/basic/app.js, specs/Modal.spec.js, src/components/Modal.js, src/components/ModalPortal.js
This patch allows users to pass custom aria attributes
to be added to the modal content.
It accepts an object where the keys are the names of the attributes
without the prefix `aria-`.
`aria` attribute is optional.
```jsx
<Modal 
...
aria={{
describedby: "Aid",
labelledby: "Bid"
}} />
```
- 
- None.
=> [added] allow users to pass aria-* attributes.

examples/basic/app.js, examples/basic/modal_a.js, examples/basic/view_a.js, examples/basic/view_b.js
=> [chore] added more examples.

specs/Modal.spec.js, src/components/Modal.js
=> [fixed] Modal.removePortal not called when using closetimeoutMS

README.md
- Change 'a11y' to 'accessibility'. This shorthand is not obvious (I had to Google it), and unnecessary (there's no character limit).
=> [chore] Change 'a11y' to 'accessibility' in README.md

specs/Modal.spec.js, src/components/ModalPortal.js
I noticed that when I wanted to animate the fadein of a modal it only worked for the first time. This was because the css animation of `ReactModal__Overlay--after-open` only works when a div is rendered for the first time. That's why I changed the logic to render nothing if there is no modal.
I'm aware that this can break a lot of things (like using a ref for `ReactModal`) for other people, so maybe we need to bump a major version if we want to have this.
- When not open, render `null` instead of `div`
When you want to use a `ref` on `ReactModal` and use it after it's rendered, you will have to place the call to the `ref` in a `setTimeout` so it's accessible after it's rendered.
This allows users to add an …
=> [changed] Don't render div on dom when isOpen is false

docs/styles/classes.md, package.json, specs/Modal.spec.js, specs/helper.js, src/components/ModalPortal.js, src/helpers/bodyClassList.js, src/helpers/refCount.js
Fixes #451.
- update `bodyOpenClassName` prop to handle adding and removing multiple class names
- update String#includes [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) to work properly
- remove unmaintained and obsolete `element-class` library
- add new helper for adding/removing classes from the body element
- update refCount helper to have a getter and chainable methods
I am using the [Tachyons](http://tachyons.io/) library for CSS styling in my app. If you have not worked with Tachyons before (it's wonderful), it is essentially a collection of atomic class names—i.e., class names that do only one thing (e.g. `.fixed { position: fixed; }`). Because of this, it is in the nature of Tachyons that multiple classes will be tacked …
=> [added] Support using multiple document.body classes

src/components/Modal.js
Fixes the following issue (Using React 16):
```js
Uncaught TypeError: Cannot read property 'state' of null
at Modal.componentWillUnmount (Modal.js:119)
at callComponentWillUnmountWithTimerInDev (react-dom.development.js:10413)
at HTMLUnknownElement.callCallback (react-dom.development.js:1209)
at Object.invokeGuardedCallbackDev (react-dom.development.js:1248)
at invokeGuardedCallback (react-dom.development.js:1105)
at safelyCallComponentWillUnmount (react-dom.development.js:10421)
at commitUnmount (react-dom.development.js:10711)
at commitNestedUnmounts (react-dom.development.js:10575)
at unmountHostComponents (react-dom.development.js:10632)
at commitDeletion (react-dom.development.js:10682)
```
Fixes #476.
- check existence of `this.portal` before trying to access it's …
=> [fixed] `Uncaught TypeError: Cannot read property 'state' of null` when unmounting

docs/README.md, specs/Modal.spec.js, src/components/Modal.js, src/components/ModalPortal.js
Fixes #306 .
- Adds a `shouldFocusAfterRender` prop, defaults to `true`
- No upgrade necessary
=> [added] Don't focus after render if we don't want to

.babelrc, package.json
In Babel 5, the ES6 default property was exported as both default
property under the CommonJS export (module.exports) and global object
(in UMD wrapper, on browser). With babel 6 this behaviour was changed
(https://github.com/babel/babel/issues/2212) and now using library
requires e.g.
require("react-modal").default instead of just require("react-modal")
ReactModal.default instead of ReactModal
This babel plugin restores the old behaviour.
Fixes https://github.com/reactjs/react-modal/issues/470
=> Export ES6 default property in CommonJS and global object

README.md, specs/Modal.spec.js, src/components/Modal.js
Fixes #479.
ARIA spec, "If the label text is visible on screen, authors SHOULD use aria-labelledby and SHOULD NOT use aria-label." 
Changing contentLabel propType to not be required; reference id for aria-labelledby will now be supported.
Won't affect existing code.
=> [fixed] Remove required flag from contentLabel propType in Modal

src/components/Modal.js
This happens when testing for `canUseDOM`.
-
- None
=> [fixed] typeof returns a string (canUseDOM).

src/components/ModalPortal.js
Fixes #515.
- Fixed drag stop on overlay closes modal
- Added moveFromContentToOverlay variable to check whether or not users drag from content to overlay
=> [fixed] Drag stop (mouseup) on Overlay closes Modal

src/components/Modal.js
`injectCSS` was deprecated since version 0.5.0.
Time to finally remove it.
- Remove warning.
- None
=> [chore] remove warning about injectCSS.

src/components/ModalPortal.js
Fixes #526 .
- Import `PropTypes` as default.
=> [fixed] Issue #526 Import PropTypes as default import.

.babelrc, package.json
This branch substitutes the usage of `babel-preset-es2015` with `babel-preset-env` as per [this recommendation](http://babeljs.io/env). Also, babel-preset-es2015 throws this warning messaging when installing:
```➜  react-modal git:(b3701f6) yarn
...
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
...
```
- [DONE] All commits have been squashed to one.
- [DONE] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [N/A] Documentation (README.md) and examples have been updated as needed.
- [N/A] If this is a code change, a spec testing the functionality has been added.
- [N/A] If the commit message has [changed] or [removed], there is an upgrade …
=> [chore] Use babel-preset-env instead of babel-preset-es2015

.eslintrc.js, package.json, specs/Modal.events.spec.js, specs/Modal.spec.js, specs/Modal.style.spec.js, specs/helper.js, specs/index.js, src/components/Modal.js, src/components/ModalPortal.js, src/helpers/ariaAppHider.js, src/helpers/bodyClassList.js, src/helpers/focusManager.js, src/helpers/refCount.js, src/helpers/safeHTMLElement.js, src/helpers/scopeTab.js, src/helpers/tabbable.js, src/index.js
- Changed `.eslintrc` to `.eslintrc.js`because it's treated with highest priority as per [the docs](https://eslint.org/docs/user-guide/configuring#configuration-file-formats), and one can do logic in JS, etc.
- Added `prettier` to the repo via `eslint` and ran it everywhere `eslint` currently runs. Any preferences on quotes or trailing commas or JSX brackets or any [other options](https://github.com/prettier/prettier#options)? Everything is currently set to defaults.
[DONE] All commits have been squashed to one.
[DONE] The commit message follows the guidelines in CONTRIBUTING.md.
[N/A] Documentation (README.md) and examples have been updated as needed.
[N/A] If this is a code change, a spec testing the functionality has been added.
[N/A] If the commit message has …
=> Added prettier and ran it where eslint runs

docs/README.md, specs/Modal.events.spec.js, src/components/Modal.js, src/components/ModalPortal.js
Fixes #481.
- Add a new prop: `shouldCloseOnEsc`
- Allow disabling of closing the modal on <kbd>esc</kbd> press.
=> [added] shouldCloseOnEsc prop

src/components/Modal.js
Check for a precise object when settings class names
(`className` and `overlayClassName`) as object.
Fixes #533.
- Define the shape of the object.
- None
=> [chore] specifiy the object when overriding class names.

src/components/ModalPortal.js
Fixes #508.
- Remove body classNames only after the modal is closed.
=> [fixed] Removes body classNames after the modal is closed.

docs/README.md, specs/Modal.spec.js, specs/Modal.style.spec.js, src/components/Modal.js, src/components/ModalPortal.js
Fixes #464.
- Adds a new prop `shouldReturnFocusAfterClose` allowing explicit control over if a modal should restore focus to the element that had focus prior to its displayed.
- Does not try to restore focus if focus wasn't transferred to the modal in the first place (`shouldFocusAfterRender` was set to `false`)
- Fixes a typo in the `Modal` props so that `shouldFocusAfter` is now correctly `shouldFocusAfterRender`
- Fixes a number of line-length warnings
=> [Fixed issue #464]

src/components/ModalPortal.js, src/helpers/focusManager.js
Both options should work independent.
If `shouldFocusAfterRender` and `shouldReturnFocusAfterClose` are `true`,
the default behavior, it should focus the modal when open and return
the focus to the previous element when close.
If `shouldFocusAfterRender` is `false` and `shouldReturnFocusAfterClose` is `true`
should be the same as both option `false` - noop.
If `shouldFocusAfterRender` is `true` and `shouldReturnFocusAfterClose` is `false`,
then we focus the modal when open and on close we just pop the previous active
element from the focus manager w/o focus.
- Both options should work independent.
- None
=> [fixed] shouldFocusAfterRender and shouldReturnFocusAfterClose flags.

specs/Modal.helpers.spec.js, specs/Modal.spec.js, specs/index.js, src/helpers/tabbable.js
Fixes #211.
When checking whether or not a node is hidden, we traverse up through the body element and say "Hey, if this element is 0x0, then it is hidden. Don't allow tabbing to its descendant." But if I, for example, position an element absolutely from its parent, theres a good chance that parent may collapse to 0x0. And if that parent has an overflow of 'visible', my input element is still visible and should be tabbable.
In our case it was `.ReactModalPortal` that was collapsing down to 0x0 and failing the `tabbable` check because it was considered `hidden`, even though our modal was visible. In this case, tabbing within a modal had no effect, as everything was descendent from the portal. My guess is most of the struggles people are having with tabbing come from a …
=> [fixed] Respect overflow css property when determining whether or not a tabbable node is hidden

examples/basic/simple_usage/index.js, src/components/ModalPortal.js
Fixes #186.
If the user doesn't allow close when clicking on the
overlay, we need to stop the event so the focus won't leave the modal
(where the key handler is defined).
- Prevent the mouse event when `shouldCloseOnOverlayClick` when set to false.
- None
=> Prevent focus from leaving modal by clicking on overlay.

CHANGELOG.md, scripts/changelog.py
Now we avoid the RCs and Alpha version, so they won't appear on the
log.
Also, now we negate the log entries that are related to releases
using a filter, which is better than exclude the first entry
using Changelog::log_in_between_versions (that way, sometimes we
remove a valid entry).
- Fix changelog writer.
- None
=> Changelog writer.

src/components/ModalPortal.js
Fixes #566.
- When `shouldCloseOnOverlayClick={false}` the `handleOverlayOnMouseDown(event)` 
must only do a `event.preventDefault()` when the click is really on the overlay.
- None
=> [fixed] shouldCloseOnOverlayClick conflict with text inputs.

README.md, package.json, specs/Modal.spec.js, src/components/ModalPortal.js, src/helpers/ariaAppHider.js
- adds aria-modal="true" to modal portal
- doesn't make body a default appElement
- warns if appElement is not set in any way
Fixes #359
Unnecesary rule: You can squash with button when merging
Unnecessary rule: You can edit commit message as well :)
=> Improve accessibility, fixes #359

.npmignore
Fixes #569.
Fixes #457.
Fixes #450.
- Ignore `.babelrc` when publishing to npm.
- None
=> [fixed] ignore .babelrc when publishing to npm.

src/helpers/focusManager.js
Fixes #577.
Without a check to see if the `focusLaterElements` array is empty, we end up calling `pop()` on an empty array—resulting in an undefined value—and inadvertently jump to the `catch` block when we attempt to call `focus()` on `undefined`.
This PR ensures that if there are no existing elements to return focus to once our modal is closed (this happens often in a testing env), we do not throw a TypeError by accident.
=> Check if focusLaterElements array is empty before popping

examples/basic/app.js, examples/basic/forms/index.js, examples/basic/multiple_modals/index.js, examples/basic/nested_modals/index.js, examples/basic/react-router/index.js, examples/basic/simple_usage/index.js, specs/Modal.events.spec.js, src/components/ModalPortal.js
Fixes #583.
- Stop event propagation when on `handleKeyDown`. This is now required when nesting modals.
- None
=> [fixed] stop propagating ESC key event.

specs/Modal.events.spec.js, src/helpers/scopeTab.js
Fixes #607.
Focusing the last tabbable element on `shift` + `tab` if the tab focus is on the modal content by checking if the shift key is active in `scopeTab` when tabbing off the modal content. Because the modal content has `tabindex="-1"`, this _should_ only happen after focus is programmatically given to the modal content on open.
=> [fixed] Tab focus escapes modal on shift + tab after opening

docs/README.md, docs/SUMMARY.md, docs/accessibility/README.md, docs/contributing/README.md, docs/contributing/development.md, docs/examples/README.md, docs/styles/README.md, docs/styles/classes.md, docs/styles/defaults.md, docs/styles/transitions.md
Addresses #576 and (partially) #454.
First of all, thank you for all your work on this project!  I recently started a project using react-modal, and I picked up a lot of information from issue comments and such that I thought would be good to include in the main documentation as well.  Please let me know if there's anything you'd like me to change!
Also, I noticed in #454 that moving documentation from the README to the book was under consideration.  If you'd like, I can update this pull request or make another one to do that, since it looks like there are only a few things that the README discusses in more detail.
* Add more information about styling CSS classes and transitions
* Add section on accessibility, including app element details (addresses #576)
* Create …
=> Expand documentation

README.md, docs/README.md, docs/SUMMARY.md, docs/accessibility/README.md, docs/styles/classes.md
Fixes #454.
This is a follow-up to PR #612; I took all the information from the README that wasn't already in the book and put it there, and then I replaced the API information in the README with a link to the book.  Let me know if there's any extra information you think is still missing from the book, and I'll add it!
- Remove duplicate information in README.md in favor of gitbook reference.
- Move remaining additional API details from README.md into gitbook.
Upgrade Path (for changed or removed APIs): N/A
=> Move API documentation from README to gitbook

docs/styles/classes.md
There is only one place that mention about the default value of the `htmlOpenClassName`.
Fixing by adding it to the [docs/styles/classes.md](https://github.com/reactjs/react-modal/blob/master/docs/styles/classes.md) page.
- None
- None
=> [chore] add to docs the default value of the html class option.

src/components/ModalPortal.js
Fixes #633
The code that should prevent the closing the modal by moving from content to the overlay was actually closing the modal `onMouseUp. By removing that part the modal only closes on an click  outside the boundaries of the content.
- Removing the onMouseUp event on the overlay element
- Removing the moveFromContentToOverlay variable from ModalPortal
=> [fixed] mouse up event on overlay triggered the closing of the modal

package.json, src/components/Modal.js
Implemented getDerivedStateFromProps and getSnapshotBeforeUpdate lifecycle methods using react-lifecycles-compat polyfill.
Fixes #637 .
Changes proposed (need some guidance with these):
- I removed the use of `prevProps` entirely according to the suggestion [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html). Which leaves us the option to use State. So I had to assign `defaultProps` to initial state and start mutating from there on.
- I implemented the `getSnapshotBeforeUpdate` method which replaces(sort of) the componentWillUpdate hook, but I'm not sure if I'm updating the `this.node` correctly?
- Now that we don't have access to `prevProps`, I'm having a trouble implementing `getParentElement` function. Since the way react works, is pass the `prevState` to …
=> removed un-safe lifecycle methods componentWillMount and componentWillUpdate

src/components/ModalPortal.js
No issue
I added defaultProp for `"defaultStyles"` prop because in render method when classname dosn't provided we are trying to access `"defaultStyles.content"` and `"defaultStyles.overlay"` properties which will cause `"TypeError"`
None
=> Added default prop for defaultStyles property

package.json
- For adapt legacy browser (e.g IE11), add `module` field to build by their own babel config with webpack, or other bundle tools.
=> Add module field to package json

src/components/ModalPortal.js
Relevant issue: #605.
Rather than allow arbitrary `data-*` attributes, I thought a simpler solution would be to have a specific prop for `testId`. Draft-js has a similar approach.
- `testId` prop for use as a test hook
- output to DOM as `data-testid` (which seems to sort of be react community standard). 
N/A
=> [added] `testId` prop for use as a test hook

specs/Modal.spec.js, src/helpers/ariaAppHider.js
Fixes #580 .
Related to #576.
- Added missing uncovered test for the scenario when a user wants to use `ReactModal.setElement("some_element"), i.e. on a string type appElement.
- Added some safety check in settlement method when there is no document due to ssr for example. It actually broke my project which uses ssr. I don't see any tests for ssr, but if for some reasons I missed them, I will be more than happy to add a test for my change.
=> [fixed]  Add missing test and a safety check for ssr

src/components/ModalPortal.js
Fixes #654.
- remove the `aria-modal` attribute set on the modal wrapper
There are a couple problems with the aria-modal attribute:
- it is not set on the correct dom element (in theory, it should be
set on the element having the dialog role, as stated in #654)
- it is buggy in Safari. The easy way to fix the problem is to remove the attribute
(again, as suggested in #654). While it's cool on paper, the attribute is currently
not necessary, since the `aria-hidden="true"` is set correctly on the
app element.
~Upgrade Path (for changed or removed APIs):~
=> Remove aria-modal attribute to prevent browser bugs

docs/styles/transitions.md
Does not fix any issue. But informs the user about the discussion in #530 
-  Update to documentation.  Inform users of `v3` be aware that close transition does not work with conditional render
=> [chore] Update doc to inform v3 users about close transition

docs/README.md, specs/Modal.spec.js, src/components/Modal.js
Fixes #653 .
- Set default value for `role`
As @afercia suggested, we should set a default value for the dialog. And omit it entirely when passing `null`.
No API changed
=> [fixed] set default role for accessibility

src/helpers/scopeTab.js
Fixes #687
- check if element is undefined before focusing it
=> [fixed] check if element exists before focusing in scopeTab helper

specs/Modal.spec.js, src/components/ModalPortal.js
Fixes https://github.com/reactjs/react-modal/issues/694
- Render `testId` prop to DOM as `data-testid={this.props.testId}` as originally implemented in: https://github.com/reactjs/react-modal/pull/646
N/A
=> [fixed] Render `testId` property

specs/Modal.testability.spec.js, specs/index.js, src/components/Modal.js
Fixes #553
See the [related comment](https://github.com/reactjs/react-modal/issues/553#issuecomment-429698010).
- Move `createPortal` method-resolution inside a method so that it can be determined at the time that it is needed. This allows developers to mock out `ReactDOM.createPortal` inside tests, which can be needed for various reasons including [react-test-renderer not supporting portals](https://github.com/facebook/react/issues/11565).
N/A
=> [fixed] Allow ReactDOM.createPortal to be mocked in tests

karma.conf.js
Changing the browser from Chrome to ChromeHeadless 
As when using chromium binary to launch chrome then getting issues
```
15 10 2018 09:29:34.292:ERROR [launcher]: Cannot start Chrome
15 10 2018 09:29:34.292:ERROR [launcher]: Chrome stdout:
15 10 2018 09:29:34.292:ERROR [launcher]: Chrome stderr:
15 10 2018 09:29:34.298:INFO [launcher]: Trying to start Chrome again (1/2).
15 10 2018 09:29:35.145:ERROR [launcher]: Cannot start Chrome
15 10 2018 09:29:35.145:ERROR [launcher]: Chrome stdout:
15 10 2018 09:29:35.146:ERROR [launcher]: Chrome stderr:
15 10 2018 09:29:35.146:INFO [launcher]: Trying to start Chrome again (2/2).
15 10 2018 09:29:35.993:ERROR [launcher]: Cannot start Chrome
15 10 2018 09:29:35.994:ERROR [launcher]: Chrome stdout:
15 10 2018 09:29:35.994:ERROR [launcher]: Chrome …
```
=> Change browser from Chrome to ChromeHeadless

docs/README.md, docs/styles/classes.md, package-lock.json, specs/Modal.spec.js, src/components/ModalPortal.js
Fixes [#[664]](https://github.com/reactjs/react-modal/issues/664) and [ #[721]](https://github.com/reactjs/react-modal/issues/721).
[#[664]](https://github.com/reactjs/react-modal/issues/664): This PR allows empty classNames for body and portal when `bodyOpenClassName ` is set with no value( `null or ""`  )
[ #[721]](https://github.com/reactjs/react-modal/issues/721): The PR also regenerates package-lock.json which fixes event-stream-3.3.6 issue caused because of the [recent security incident ](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)
=> [fixed] Allow empty classNames for body

docs/README.md, specs/Modal.events.spec.js, src/components/ModalPortal.js
Fixes #708 .
Since the `onRequestClose` won't be executed when `isOpen` changes outside of the controller scope, I think it's reasonable to give a single handler to general closing.
This would allow for some more centralised solutions like:
```js
const modalProps = {
onAfterOpen: disableBodyScroll,
onAfterClose: enableBodyScroll,
}
```
whereas today you have to do:
```js
const modalProps = {
onAfterOpen: disableBodyScroll,
onRequestClose:  enableBodyScroll
}
closeModal () {
this.setState({ isOpen: false })
enableBodyScroll();
}
```
- Introduce `onAfterClose` callback prop
=> [added] Introduce onAfterClose callback prop

package-lock.json, package.json
Fixes #744 
- Downgraded `webpack-dev-server` to `2.11.5` which is the latest version that supports `webpack 3`
Upgrade Path (for changed or removed APIs): N/A
=> [fixed] Local development environment

docs/README.md, specs/Modal.spec.js, src/components/ModalPortal.js
Fixes #763 
- Adding an 'id' prop to be passed to the dialog component
=> [added] Added an id prop, applied to the modal dialog (content)

.gitignore, specs/Modal.events.spec.js, src/components/ModalPortal.js
Fixes #745
- `onAfterClose` prop will no longer be triggered when unmounting a closed modal, but will still be when unmounting an opened modal.
- Added `.vscode` folder to `.gitignore`
Upgrade Path (for changed or removed APIs): N/A
=> [fixed] onAfterClose prop called when unmounting a closed modal

specs/Modal.helpers.spec.js, src/helpers/tabbable.js
Fixes #732 
The bug in the example stems from the `hidesContents` function in `tabbable.js` returning false on the button with the `display: none` inline style. It is returning false because the element has the computed style `overflow: visible` (which is default value). 
The problem with this is that having `overflow: visible` doesn't mean there is any content that is  overflowing. 
I think there are a couple possible ways to fix this. One would be to add an additional check for the `display: none` style if `zeroSize === true`, which would directly solve the bug in the example.
I'm not sure that will catch every possibility, so instead I check the elements `scrollWidth` and `scrollHeight` to determine whether or not there is any overflowing content.
Acceptance …
=> [fixed] some untabbable elements are being returned from findTabbable

specs/Modal.events.spec.js, src/components/ModalPortal.js
Fixes #739 .
- Pass `overlay` and `content` references to `onAfterOpen` prop fn
=> [added]: pass overlay and content element references to onAfterOpen fn

src/components/Modal.js
Fixes #769 
Should we also check before calling removeChild here (In `componentDidUpdate()`? 
```
const { prevParent, nextParent } = snapshot;
if (nextParent !== prevParent) {
prevParent.removeChild(this.node);
nextParent.appendChild(this.node);
}
```
I'm fairly new to contributing to open-sourced projects. Please let me know if I made any mistakes. Thank you!
---
=> [fixed] Call parent.removeChild only if parent exists

README.md
Fixes #784 .
+ Add hook component
- Delete class component
=> Update README (example with React Hooks)

src/components/ModalPortal.js, src/helpers/bodyTrap.js, src/helpers/portalOpenInstances.js
Fixes #742
- Ensure modal focus trap when reentering document. This restores modal focus when navigating into the page by keyboard. See discussion on #742 and #787
- N/A
- ~[ ] Documentation (README.md) and examples have been updated as needed.~ *N/A I think*
- ~[ ] If the commit message has [changed] or [removed], there is an upgrade path above.~ *N/A I think*
=> [fixed] Focus trap when reentering document (#742)

docs/examples/set_app_element.md
The docs has an invalid URL, and this commit sets the correct link.
=> [fixed] set correct URL for codepen setAppElement example

docs/examples/css_classes.md, docs/examples/global_overrides.md, docs/examples/inline_styles.md, docs/examples/minimal.md, docs/examples/on_request_close.md, docs/examples/should_close_on_overlay_click.md
Signed-off-by: isamrish <askmaurya48@gmail.com>
This commit will fix broken codepen urls in examples files of docs. Those md
files are following
- css_classes.md
- global_overrides.md
- inline_styles.md
- minimal.md
- on_request_close.md
- should_close_on_overlay_click.md
=> [fixed] - Fix broken links of codepen in examples in docs

src/components/ModalPortal.js
In IOS we found that the focus of an element would scroll the page so such element is brought into view.
In our case we have a grid of several views (iframes) and whenever a modal would appear on one of those views then the whole app would scroll to show the cell were the modal appeared, which is undesireable.
This PR fixes that.
=> [fixed] - Ensure focus does not scroll the modal

docs/index.md
- Added `testId` prop existence and usage to documentation
=> Added testId prop and usage to documentation

src/components/Modal.js
Fixes #824
- Access `ReactDOM.createPortal` via a function instead of directly, so it is only accessed when required, not when the script is compiled. Stops errors being thrown when bundled into script that is run in an environment without access to ReactDOM.
N/A
=> [fixed] lazily access ReactDOM.createPortal

docs/index.md
Fixes #830 by removing what I think is a typo: the character 'p' at the beginning of the "Using a custom parent node" on react-modal's documentation page.
- Updating [`index.md`](https://github.com/reactjs/react-modal/blob/master/docs/index.md) to remove what I think is a typo.
I don't think this is applicable.
=> [fixed] extra 'p' character in index.md

src/components/ModalPortal.js
As it said in the [comment](https://github.com/reactjs/react-modal/issues/654#issuecomment-672640981) of #654 Safari has no longer problem with aria-modal='true'
Without aria-modal, React Testing library seems have some troubles to find de modal role.
Now, with the current version of the code of React-modal and Safari, the modal seems to be able to be reintroduce.
=> [fixed] add aria-modal attribute

docs/styles/classes.md
All this does is change the "default content styles" hyperlink to `index.md` instead of `README.md`, since I think the link to `README.md` is stale since at least [Dec 9, 2019](https://github.com/reactjs/react-modal/tree/e5fe406111f97269b8a552e9fc5ee285e05941fa/docs/styles) with commit e5fe406111f97269b8a552e9fc5ee285e05941fa.
Fixes #833.
- Update "default content styles" hyperlink in [`classes.md`](https://github.com/reactjs/react-modal/blob/master/docs/styles/classes.md) to link to `index.md` instead of `README.md`
I don't think this is applicable for this pull request.
=> [fixed] stale link in react-modal/docs/styles/classes.md

docs/accessibility/index.md, specs/Modal.spec.js, src/components/Modal.js, src/components/ModalPortal.js, src/helpers/ariaAppHider.js, src/helpers/safeHTMLElement.js
**Changes proposed:**
- Hide multiple app elements, not just one
- Accept Array, HTMLCollection & NodeList values for the `appElement` prop
While working with an application that uses more than one top-level element, it became obvious that providing a fully accessible experience via react-modal is challenging, as it's currently only able to hide one app element.
The fix for this is pretty simple, and should have no effect on existing users. The accepted shape of the `appElement` value now also includes Array, HTMLCollection (returned by `document.getElementsBy*`) and NodeList (returned by `document.querySelectorAll`).
As a result of this change, it becomes easier to use react-modal to provide a fully accessible experience.
**Acceptance Checklist:**
=> [added] support Array, HTMLCollection and NodeList values for appElement

specs/Modal.events.spec.js, specs/Modal.spec.js, specs/Modal.style.spec.js, specs/Modal.testability.spec.js, specs/helper.js, src/components/Modal.js, src/helpers/ariaAppHider.js, src/helpers/bodyTrap.js, src/helpers/classList.js, src/helpers/focusManager.js, src/helpers/portalOpenInstances.js
When a test fails, if all the resources are not properly disposed, they can impact other tests.
In this case, they are mostly HTMLElement that are not been removed from the document.
Now we have an automatic way to dispose any element resource and modal.
None
None
=> [chore] added tracing and helpers to avoid element leaks.

package-lock.json, package.json
- upgrade prop-types dependency to 15.7.2 
- this upgrade remediates a high risk vulnerability identified in transitive dependency ua-parser-js
- see: [https://snyk.io/test/npm/ua-parser-js/0.7.21](https://snyk.io/test/npm/ua-parser-js/0.7.21?tab=issues )
=> bump prop-types to 15.7.2

src/components/ModalPortal.js
Fixes #882 .
- Be sure to cancel the animation frame that is requested in the ModalPortal open method so that a state change is not potentially requested after the component is unmounted.
In the issue description I mentioned that `isMounted` might be a potential fix, but then I [read that it is an antipattern](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html). The `componentWillUnmount` method is already clearing a timeout, so canceling the animation seems like the best option.
I can confirm that these changes fix the error message I was seeing in the jest/testing-library environment I am using in a separate project. It is unclear to me how to reproduce this race condition in the testing setup used in this project. Any ideas would be appreciated.
Acceptance …
=> [fixed] Cancel requested animation frame on unmount.

package-lock.json, package.json, specs/Modal.helpers.spec.js, src/helpers/scopeTab.js, src/helpers/tabbable.js
When inside a Shadow DOM, the loop will eventually reach the Shadow DOM element itself, which cannot be checked for visibility. We can continue our upwards check by skipping to the Shadow DOM host.
- Skip the Shadow DOM element (`rootNode` when inside a Shadow DOM) when checking for visibility.
- Ensure that we know about every tabbable element, even those within Shadow DOM.
=> [fixed] Ensure we don't check for hidden on Shadow DOM.

src/helpers/tabbable.js
Iframes are, just like a button, anchor or inputs, an interactive element that should be focusable in modal. For example I play youtube videos in modals. Keyboard users should be able to pause video (or trigger any other action) as well.
- add `iframe` to list of tabbable elements
N/A
=> [added] tabbable support for iframes

docs/index.md, src/components/ModalPortal.js
Fixes [#[964]](https://github.com/reactjs/react-modal/issues/964)
I am trying to open the modal inside an iframe, but the `bodyOpenClassName` would be applied to the rootDocument instead.
I would like to use the parentSelector to determine where the `bodyOpenClassName` should be added instead of just using `document.body`
- `htmlOpenClassName` add to the modal ownerDocument html instead
- `bodyOpenClassName` add to the modal ownerDocument body instead
- Update doc 
=> [fixed]: css class added to root document instead of modal ownerDocument

README.md
Fixes #967.
- update broken build badge
- (note that the badge LINK is still broken)
n/a
=> update broken build badge

src/helpers/tabbable.js
Fixes #905.
This PR is a follow-up of https://github.com/reactjs/react-modal/pull/906 addressing the PR feedback.
- element with display 'contents' is visible and is tabbable.
- none
=> [fixed] element with display 'contents' is visible and is tabbable

package-lock.json, specs/Modal.events.spec.js, specs/helper.js, src/components/ModalPortal.js
Fixes #952.
- Switch keydown event listeners to use `KeyboardEvent.code`. The legacy `KeyboardEvent.keyCode` is deprecated. Since React 18 dropped support for IE, we don't need to fall back on it, and can simply switch to the new property
- More context: see #952 
- ~Documentation (README.md) and examples have been updated as needed.~
- ~If this is a code change, a spec testing the functionality has been added.~
- ~If the commit message has [changed] or [removed], there is an upgrade path above.~
=> [fixed] switched from KeyboardEvent.keyCode to KeyboardEvent.code

package-lock.json, package.json, specs/Modal.events.spec.js, specs/Modal.spec.js, specs/helper.js, src/components/Modal.js, src/helpers/ariaAppHider.js
Fixes #988.
- One of the options to set the app element are going to be required
because we can't use `document.body` as default (hides all elements on the page).  
- Must use one of the options.
=> Fixed/988 - Make setAppElement or appElement required

CONTRIBUTING.md, package.json
Fixes #1022 ].
- added Miscellaneous section to the contribution.md file to point out that you need nodejs version 16 to start the project 
- [x ] The commit message follows the guidelines in `CONTRIBUTING.md`.
=> [added] add Miscellaneous section to the contributions.md file

docs/index.md
Super simple change, but it is to ensure proper syntax highlighting in http://reactcommunity.org/react-modal/
Right now it's showing error on the ellipsis because it's not a valid entity in JSX. This also affects the line after the ellipsis.
Once the ellipsis is commented out, the syntax highlighting should become correct for the line after it.
- Comment the ellipsis in code blocks in docs/index.md
=> Comment the ellipsis in code blocks in docs/index.md

docs/index.md
- updated documentation of the `shouldCloseOnOverlayClick` prop
=> chore: update shouldCloseOnOverlayClick doc
