README.md

:memo: link to demos

---

lib/components/Modal.js

See https://github.com/facebook/react/issues/3713 and
https://github.com/facebook/react/issues/2770

Returning noscript tag instead of null

---

package.json

move exenv to dependencies

---

CHANGELOG.md
lib/components/Modal.js
lib/components/ModalPortal.js
lib/helpers/focusManager.js
specs/Modal.spec.js

Very minor/nit things I noticed while digging through the code.

Fix a couple typos/misspellings/missing semi

---

examples/basic/app.css
examples/bootstrap/app.css

Minor improvement to the demo.

Improve example CSS for non-Webkit browsers

---

scripts/dev-examples

Useful for people who develop in virtual machines.

Dev server listens on all interfaces

---

lib/components/ModalPortal.js
specs/Modal.spec.js

This PR addresses issue #115.
https://css-tricks.com/dangers-stopping-event-propagation/

Avoid stopPropagation

---

lib/components/ModalPortal.js
specs/Modal.spec.js

[added] Propagate event on close request

---

examples/basic/app.js
lib/components/Modal.js

Fixes #165.
- Remove sanitizeProps
The sanitize props function seems to be unneeded and there
is no concrete explanation for why it is there.  This removes
it to prevent problems caused by calling it.

[fixed] Removes unneeded sanitizeProps function

---

package.json

[fixed] Add missing envify npm dependency. Closes #193

---

lib/components/ModalPortal.js
specs/Modal.spec.js

Fixes #212.
- Make the dialog role be present on the modal content.

[added] Make modal portal have the dialog role

---

lib/components/Modal.js

Fixes #268
- Remove arrow function
- N/A

[fixed] Remove arrow function from ES5 source

---

LICENSE

- Updates copyright year to current year
-
-

[changed] Updates License

---

examples/basic/app.js
lib/components/ModalPortal.js
lib/helpers/focusManager.js
specs/Modal.spec.js
specs/helper.js

This PR improves reliability to give back focus
to parent modal.
- empty

[change] improve reliability on focus management.

---

README.md

Add gzip size badge

---

.gitignore
.travis.yml
Makefile
package.json
scripts/build
scripts/dev-examples
scripts/preview-release
scripts/release
scripts/test
scripts/version

This would make easier to build and publish.
To succeed, this PR should publish itself.

[chore] improving build and publish pipeline.

---

examples/basic/app.js

While we don't move to v2, we can use Object.assign
and later use the spread operator.

[fixed] use Object.assign for now.

---

Makefile
bootstrap.sh
scripts/version

Prevent publish if an error occur.

[chore] prevent publish if an error occur.

---

README.md

Added travis ci build status on README.md.

[chore] add travis ci build status on README.md.

---

.gitignore
Makefile

refactor and clean up build system.
* added .version and .branch to .gitignore...
this allow us to write files once with the new version,
and now, the branch which the version will be released.
when it finishes to publish, remove both files.
* execute tests before publish was missing.
* publish assets were not removed.

[chore] refactor and clean up build system.

---

README.md

This is a patch, by @OliverJAsh, available on `master` to add a gzip size badge.

[chore] add gzip size badge.

---

Makefile

Improve publish docs commands.

[chore] improve publish docs commands.

---

README.md

[chore] update README.md.

---

.travis.yml

Don't test on node versions < 6.x.y.

[chore] don't test on node versions < 6.x.y.

---

docs/SUMMARY.md
docs/dev/README.md

added documentation for development.

[chore] added documentation for development.

---

.github/ISSUE_TEMPLATE.md

-  Add codesandbox link to the ISSUE_TEMPLATE so we have a common template to build verifiable issue examples against.

[added] Add codesandbox link to the ISSUE_TEMPLATE

---

README.md

We can remove the `active development` now.

[chore] removing active development section.

---

README.md

Update `README.md` to include installation using `yarn`.

[chore] update installation section.

---

specs/Modal.spec.js

[chore] added test for default parentSelector.

---

package.json

[chore] allow latest version for exenv dependency

---

src/components/ModalPortal.js

[fixed] Dragging inside modal and release outside of modal closes the modal

---

README.md

- Use JSX syntax for code examples in README.md

README.md: update syntax flavour to jsx

---

CHANGELOG.md

Fixes #477 #483.
- None
- None

[chore] Rebuild changelog.

---

docs/README.md

[chore] Update description for onRequestClose.

---

examples/base.css
examples/basic/app.js
examples/basic/forms/index.js
examples/basic/index.html
examples/basic/multiple_modals/index.js
examples/basic/simple_usage/index.js
examples/basic/simple_usage/modal.js
examples/bootstrap/app.js
examples/bootstrap/index.html
examples/index.html
webpack.config.js

Update tests.
- Improve (a little) design.
- Fix folders.
- Update bootstrap example.
- None

[chore] update tests.

---

examples/basic/app.js
examples/basic/react-router/index.js
package.json
webpack.config.js

From #499.
- Show how to use `react-modal` with `react-router`.
- None

[chore] added example with react-router.

---

examples/basic/multiple_modals/index.js

Fix multiple modal example.
- Make it work
- None

[chore] fix multiple modal example.

---

examples/base.css

[chore] improve examples style.

---

src/components/Modal.js
src/helpers/safeHTMLElement.js

- Already implemented in this package.
- None.

[chore] use canUseDOM from exenv.

---

src/helpers/ariaAppHider.js

Fixes the prettier merge issue referenced in [this PR](https://github.com/reactjs/react-modal/pull/529).
- [DONE] All commits have been squashed to one.
- [DONE] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [N/A] Documentation (README.md) and examples have been updated as needed.
- [N/A] If this is a code change, a spec testing the functionality has been added.
- [N/A] If the commit message has [changed] or [removed], there is an upgrade path above.
@diasbruno basically I forgot to run prettier after I resolved the merge conflict in [this PR](https://github.com/reactjs/react-modal/pull/525). Not sure if Travis ran after I updated my branch in that PR?

[chore] fix prettier linting after merge issue

---

.travis.yml

Run tests only on node 8.
- None
- None

[chore] run tests only on node 8.

---

examples/basic/app.js
examples/basic/forms/index.js
src/helpers/scopeTab.js

Fixes #511.
This is still wip, for test only.
- fix the logic to walk on "tabbable" elements inside the modal.
- None

[fixed] correctly walk when using TAB.

---

README.md

[chore] remove code climate badge from readme.

---

README.md

[chore] added badge to react-modal gitter channel.

---

src/helpers/ariaAppHider.js

- replaces `reades` to `readers`

typo in word

---

README.md
docs/styles/README.md

I want to add this clarification about the `style` prop. I wasted a bit of time because I had to assume the prop was styles, before finally realising it is `style` so I've enhanced the example with a real use case
-
-
-

updates README - styles

---

examples/bootstrap/app.js
examples/bootstrap/index.html

Fixes #597.
- Bump bootstrap example to use 4.0 release
- Update the bootstrap example to use the latest bootstrap modal format

Bump bootstrap example to use 4.0 release

---

specs/Modal.events.spec.js

First PR, starting small.
- Corrects minor typos in Modal.events.spec.js

Fix minor typos in spec

---

README.md
docs/README.md
specs/Modal.spec.js
src/components/Modal.js
src/components/ModalPortal.js

Fixes #478
Add ref callbacks for overlay and content

[added] ref for overlay and content

---

README.md

I made a mistake in PR #613, and this is the fix.  Sorry about that!
- Update table of contents in README.md to reflect new contents.
Upgrade Path (for changed or removed APIs): N/A

[chore] Fix README table of contents

---

docs/examples/should_close_on_overlay_click.md

Fixes #620.
- improve documentation for `shouldCloseOnOverlayClick`
- None

[chore] improve documentation for shouldCloseOnOverlayClick.

---

.eslintrc.js
package.json
src/components/Modal.js
src/components/ModalPortal.js

Fixes #637 
See https://github.com/reactjs/react-modal/pull/639/files/67a74bd23915960d5421d6b9c77b6ab7a47675b4#diff-476e2e918a31cbbf34324b08ddeee24e

Fix lifecycle methods usages

---

package.json

Fixes #650.
- Fix the module path in package.json.
- None

[fixed] incorrect path for module in package.json.

---

src/helpers/scopeTab.js

- corrected spelling in comment
-

[fixed] very small spelling correction in comment

---

package-lock.json
package.json

Update `webpack-dev-server` dependency.

[chore] update webpack-dev-server dependency.

---

package-lock.json
package.json

Update `warning` to v4

---

README.md

Add '--save'

---

package-lock.json
package.json

- Added react 17 support - no breaking changes from 16 to 17 so should just be a simple one

Added react 17 support

---

README.md

- Updated format of the example in the main README

Doc: Format example

---

README.md
docs/index.md

Fixes #[889].
- Noticing cdn install in docs because I'd to check <ReactModal> tag in docs example but didn't see this in Installation section :)
Upgrade Path (for changed or removed APIs): -

Update documentation by my suggestion in #889

---

examples/wc/app.css
examples/wc/app.js
examples/wc/index.html
specs/Modal.helpers.spec.js
src/helpers/tabbable.js

Fixes #1014.
- Make node name matcher more strict to search whole word, not partial
- Added example with a web component

[fixed] strict matching for tabbable nodes
